### Match with real values

In [17]:
import pandas as pd 
import re
pathreal = './adult.csv'
path = '/home/sonia/be_great/ckpts/great/adult/moedgpt2-aug13-2/samples'

age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income

### From text

In [18]:
raws = []
with open(path+'.txt', 'r') as f:
    for raw in f.readlines():
        raws.append(re.sub('is\?', 'is ?', raw))

In [19]:
l = raws[0]
problem = 0
def parse_line(l):
    cols = l.split('.<EOS>')[:-1] # remove newline at end
    words = [c.split(' ') for c in cols] #'name', 'is', 'value'
    if len(words) == 15:
        return {c[0]:c[2] for c in words}
    else:
        problem += 1
        return {}

line_dicts = [parse_line(l) for l in raws]
df = pd.DataFrame.from_records(line_dicts)
print(problem, 'problem lines')
df

0 problem lines

,income,sex,occupation,class,years-education,race,relationship,age,marital-status,education,gain-capital,hours-per-week,loss-capital,financial-weight,native-country
0,<=50K,Male,Other-service,Private,9,White,Unmarried,37,Divorced,HS-grad,0,45,0,246872,United-States
1,>50K,Male,Prof-specialty,Private,13,White,Husband,59,Married-civ-spouse,Bachelors,15024,40,0,157928,United-States
2,<=50K,Female,Other-service,Private,9,White,Wife,27,Married-civ-spouse,HS-grad,0,40,0,93032,United-States
3,<=50K,Male,Prof-specialty,Private,10,White,Own-child,20,Never-married,Some-college,0,40,0,174520,United-States
4,<=50K,Male,Craft-repair,Private,9,White,Not-in-family,25,Separated,HS-grad,0,40,0,407422,United-States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,<=50K,Male,Sales,Private,9,White,Not-in-family,23,Never-married,HS-grad,0,30,0,156903,United-States
9996,<=50K,Female,Exec-managerial,Private,13,White,Unmarried,20,Separated,Bachelors,0,45,0,216460,United-States
9997,<=50K,Female,Adm-clerical,Private,10,White,Not-in-family,41,Divorced,Some-college,0,40,0,52849,United-States
9998,<=50K,Female,Machine-op-inspct,Private,10,White,Not-in-family,20,Never-married,Some-college,0,40,0,117774,United-States
9999,>50K,Male,Protective-serv,Private,10,White,Husband,52,Married-civ-spouse,Some-college,0,50,0,115038,United-States

In [20]:
cols = ['age', 'class', 'financial-weight', 'education', 'years-education', 'marital-status', 'occupation', 'relationship', 
        'race', 'sex', 'gain-capital', 'loss-capital', 'hours-per-week', 'native-country', 'income']
colsgreatreal = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 
        'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country', 'income']
colsdict = {g:r for (g,r) in zip(cols, colsgreatreal)}
df.columns = [colsdict[c] for c in df.columns]
df = df[colsgreatreal]
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,37,Private,246872,HS-grad,9,Divorced,Other-service,Unmarried,White,Male,0,0,45,United-States,<=50K
1,59,Private,157928,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,15024,0,40,United-States,>50K
2,27,Private,93032,HS-grad,9,Married-civ-spouse,Other-service,Wife,White,Female,0,0,40,United-States,<=50K
3,20,Private,174520,Some-college,10,Never-married,Prof-specialty,Own-child,White,Male,0,0,40,United-States,<=50K
4,25,Private,407422,HS-grad,9,Separated,Craft-repair,Not-in-family,White,Male,0,0,40,United-States,<=50K

### From csv

In [21]:
# df=pd.read_csv(pathgreatdgpt2+'.csv')
# df['income'] = df['income'].apply(lambda x: x.strip())
# df.head()

In [22]:
real = pd.read_csv(pathreal)
colsgreatreal = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 
        'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country', 'income']
real.columns = colsgreatreal
ords = ['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'native-country', 'income']
ordvals = {col:set(real[col].unique()) for col in ords}
for col in ordvals:
    ordvals[col] = [val.strip() for val in ordvals[col]]
# ordvals

In [23]:
for col in ordvals:
    df = df[df[col].isin(ordvals[col])]
    print(col, len(df))
# df[[df[col].isin(ordvals[col]) for col in ordvals]]
df
# df=df[df['workclass'].isin(ordvals['workclass']) & df['income'].isin(ordvals['income'])]
# df.head()

workclass 10000
education 9999
marital-status 9999
occupation 9999
relationship 9999
race 9999
sex 9999
native-country 9999
income 9999

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,37,Private,246872,HS-grad,9,Divorced,Other-service,Unmarried,White,Male,0,0,45,United-States,<=50K
1,59,Private,157928,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,15024,0,40,United-States,>50K
2,27,Private,93032,HS-grad,9,Married-civ-spouse,Other-service,Wife,White,Female,0,0,40,United-States,<=50K
3,20,Private,174520,Some-college,10,Never-married,Prof-specialty,Own-child,White,Male,0,0,40,United-States,<=50K
4,25,Private,407422,HS-grad,9,Separated,Craft-repair,Not-in-family,White,Male,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,23,Private,156903,HS-grad,9,Never-married,Sales,Not-in-family,White,Male,0,0,30,United-States,<=50K
9996,20,Private,216460,Bachelors,13,Separated,Exec-managerial,Unmarried,White,Female,0,0,45,United-States,<=50K
9997,41,Private,52849,Some-college,10,Divorced,Adm-clerical,Not-in-family,White,Female,0,0,40,United-States,<=50K
9998,20,Private,117774,Some-college,10,Never-married,Machine-op-inspct,Not-in-family,White,Female,0,0,40,United-States,<=50K
9999,52,Private,115038,Some-college,10,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,50,United-States,>50K

In [24]:
df.to_csv(path+'clean.csv', index=False)